
// Objective-C API for talking to the following Go packages
//
//	github.com/jmayalag/prifi/prifi-mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __PrifiMobile_FRAMEWORK_H__
#define __PrifiMobile_FRAMEWORK_H__

#include "PrifiMobile.objc.h"
#include "universe.objc.h"

#endif
